### ISSUE TITLE
Duplicate 'import re as _re' in stage8_aggregate/aggregate.py (already imported at line 105)

### ISSUE THREAD

**Issue by ianmmc** [ianmmc/learning-connection-time#791]
> Found during max-effort multi-agent `/code-review` of PR #774 (2026-08-16). Introduced by PR #774 (fix/693-721-roster-anchored-identity).

## The observation

`stage8_aggregate/aggregate.py` adds a second, identical `import re as _re` at line ~112; the module already imports it at line 105 (independently confirmed by 5 separate review passes and pyflakes).

## Failure scenario

No runtime effect (Python tolerates re-import; pyflakes flags it as "redefinition of unused '_re' from line 105"), but it signals the new block was written without checking existing imports.

## Suggested fix direction

Delete the line-112 import.

## Acceptance (falsifiable)

`pyflakes infrastructure/acquisition/stage8_aggregate/aggregate.py` reports no redefinition warning for `_re`.
